--================================================================CREATE USER SQL-LOGIN(SERVER_LEVER)
--======================================USE master
USE master;
GO
-- CREATE USER
CREATE LOGIN USER_KY_THUAT
	WITH PASSWORD = N'111111',
    CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF,
    DEFAULT_DATABASE = DLHI_V2;
GO

--================================================================CREATE ROLE IN MY DATABASE
--======================================USE <MY_DATABASE>
-- CREATE THE ROLE
USE DLHI_V2

-- CREATE A DATABASE USER FOR THAT LOGIN
GO
CREATE USER USER_KY_THUAT FOR LOGIN USER_KY_THUAT
GO

-- CREATE ROLE
CREATE ROLE KY_THUAT_ROLE;

-- GRANT TABLE PERMISSIONS
GRANT SELECT, INSERT, UPDATE ON SCHEMA::dbo TO KY_THUAT_ROLE;
GRANT EXECUTE TO KY_THUAT_ROLE;
GRANT CONNECT TO KY_THUAT_ROLE;

-- DENY TABLE MODIFICATION PERMISSIONS
DENY ALTER TO KY_THUAT_ROLE;
DENY CONTROL TO KY_THUAT_ROLE;
DENY CREATE TABLE TO KY_THUAT_ROLE;
 
-- ADD ROLE FOR USER
ALTER ROLE KY_THUAT_ROLE ADD MEMBER USER_KY_THUAT;


-- INSERT ROLE INTO TABLE STAFF_ROLE
INSERT INTO STAFF_ROLE (ID, ROLE_NAME, ROLE_ACTION)
VALUES ('8d0d2aa6-e7f2-425d-b740-da520403f552', 'KY_THUAT_ROLE', '')
-- INSERT TABLE DEPARMENT
INSERT INTO DEPARMENTS (ID, DEP_CODE, DEP_NAME)
VALUES ('1c83494d-f5fd-42be-a5ca-b7ba3860ae88', 'KT', 'KY_THUAT_ROLE')
-- INSERT USER INTO TABLE STAFFS
INSERT INTO STAFFS (ID, STAFF_CODE, STAFF_PWD, STAFF_NAME, DEPARMENT_ID)
VALUES ('0893ff15-c411-455d-b886-60da937821ce', 'KT001', N'111111', N'KT TEST', '1c83494d-f5fd-42be-a5ca-b7ba3860ae88')

-- UPDATE ROLE_ID FOR USER
UPDATE STAFFS SET STAFF_ROLE_ID = '8d0d2aa6-e7f2-425d-b740-da520403f552' WHERE ID = '0893FF15-C411-455D-B886-60DA937821CE'	
--EXEC sp_addrolemember 'KY_THUAT_ROLE', 'USER_KY_THUAT';

SELECT name, state_desc FROM sys.databases WHERE name = 'DLHI_V2';
