-------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------
-- Get product for create MPR
GO
CREATE PROC GET_PRODUCTS
AS
BEGIN
	SELECT PRODUCTS.ID, PRODUCT_NAME, PRODUCT_DES_2, PRODUCT_CODE, PRODUCT_MATERIAL_CODE, PICTURE,
		A_THINHNESS, B_DEPTH, C_WIDTH, D_WEB, E_FLAG, F_LENGTH, G_WEIGHT, UNIT_CODE, USED_NOTE,
		PICTURE_LINK, PRODUCTS.UNIT_ID AS UNIT_ID, ORIGIN_ID, M_TYPE_ID, STANDARD_ID
	FROM PRODUCTS, UNITS
	WHERE PRODUCTS.UNIT_ID = UNITS.ID
END
GO
EXEC GET_PRODUCTS

-- Get MPR detail
GO
CREATE PROC GET_MPR_DETAIL @MPR_ID UNIQUEIDENTIFIER 
AS
BEGIN
	SELECT MPR_DETAIL.ID, MPR_DETAIL.MPR_ID, MPR_DETAIL.PRODUCT_ID, PRODUCTS.PRODUCT_NAME, PRODUCTS.PRODUCT_DES_2, PRODUCTS.PRODUCT_MATERIAL_CODE,
		PRODUCTS.A_THINHNESS, PRODUCTS.B_DEPTH, PRODUCTS.C_WIDTH, PRODUCTS.D_WEB, PRODUCTS.E_FLAG, PRODUCTS.F_LENGTH, PRODUCTS.G_WEIGHT, 
		MPR_DETAIL.MPR_QTY, MPR_DETAIL.USAGE, MPR_DETAIL.ISSUE_DATE, MPR_DETAIL.MPR_REMARKS
	FROM MPR_DETAIL, PRODUCTS
	WHERE MPR_DETAIL.PRODUCT_ID = PRODUCTS.ID
		AND MPR_DETAIL.MPR_ID = @MPR_ID
END
GO
EXEC GET_MPR_DETAIL 'D33643B1-B29A-457A-92D3-2AF7916AE272'
SELECT *FROM MPR_DETAIL WHERE MPR_ID = '29e2b4ba-e7c5-4de2-b209-9f08c8803496'

-- Get PO detail
GO
CREATE PROC GET_POS 
AS
BEGIN
	SELECT POS.ID, PO_NO, PO_MPR_NO, PO_WO_NO, PO_PROJECT_NAME, PO_REV_TOTAL, PO_CREATE_DATE, PO_EXPECTED_DELIVERY_DATE, PO_PREPARED,
		PO_REVIEWED, PO_AGREEMENT, PO_APPROVED, PO_PAYMENT_TERM, PO_PLACE_OF_CONTRY, PO_TOTAL_AMOUNT,
		COST.COST_NAME, TAX.TAX_PERCENT, SUPPLIERS.NAME
	FROM POS, COST, TAX, SUPPLIERS
	WHERE POS.COST_ID = COST.ID AND POS.TAX_ID = TAX.ID AND POS.SUPPLIER_ID = SUPPLIERS.ID
END
GO
EXEC GET_POS

-- Get PO detail
GO
CREATE PROC GET_PO_DETAIL @PO_ID UNIQUEIDENTIFIER 
AS
BEGIN
	SELECT PO_DETAIL.ID, PO_DETAIL.PO_ID, PO_DETAIL.PO_PRODUCT_ID, PRODUCTS.PRODUCT_NAME, PRODUCTS.PRODUCT_DES_2, PRODUCTS.PRODUCT_MATERIAL_CODE,
		PRODUCTS.A_THINHNESS, PRODUCTS.B_DEPTH, PRODUCTS.C_WIDTH, PRODUCTS.D_WEB, PRODUCTS.E_FLAG, PRODUCTS.F_LENGTH, PRODUCTS.G_WEIGHT, 
		PO_DETAIL.PO_QTY AS PO_DETAIL_QTY, PO_DETAIL.PO_PRICE AS PO_DETAIL_PRICE, PO_DETAIL.PO_AMOUNT AS PO_DETAIL_AMOUNT
	FROM PO_DETAIL, PRODUCTS
	WHERE PO_DETAIL.PO_PRODUCT_ID = PRODUCTS.ID
		AND PO_DETAIL.PO_ID = @PO_ID
END
GO
EXEC GET_PO_DETAIL 'B8B8C805-C2D7-489F-8A1A-87F02079F914'
SELECT *FROM POS
SELECT *FROM POS WHERE PO_CREATE_DATE >= '2025-04-12 00:00:00.000' AND PO_EXPECTED_DELIVERY_DATE <= '2025-04-12 00:00:00.000'